### ISSUE TITLE
Python KeyError: 'code'

### ISSUE THREAD

**Issue by atmoner** [MattMcFarland/battlefield-companion#1]
First, thanks for your work!
When i try to run token.py file, i get this error

```
Error: Command failed: python /home/atmoner/Bureau/bf/node_modules/battlefield-companion/python/token.py contact.****@gmail.com *******
Traceback (most recent call last):
  File "/home/atmoner/Bureau/bf/node_modules/battlefield-companion/python/token.py", line 30, in <module>
    EA_AUTH_CODE = json.loads(SESSION.get(EA_AUTH_URL).text)['code']
KeyError: 'code'
```
Any idea?

**Comment by MattMcFarland** [comment]
EDIT: nevemrind sorry, it looks like JSON is not valid.  Can you log out what EA_AUTH_CODE is?

**Comment by atmoner** [comment]
I can not debug `EA_AUTH_CODE` because it is the content of this variable that causes the problem!
If i remove `['code']` The code continues but generates a login error (which is normal)

**Comment by MattMcFarland** [comment]
Ok, thanks!  I'll see if I can reproduce (they might have updated their API)

**Comment by atmoner** [comment]
Mhh! login problem when i print (without ['code']):
`print json.loads(SESSION.get(EA_AUTH_URL).text)`

I get:
`{u'error': u'login_required'}`

I have try with this python script: https://github.com/inclementweather/bfcompanionpy/blob/master/bfcompanion.py  
but same problem... Login error

I have check my crendential but for me it's ok....
Can you try to login your account with [bfcompanion.py](https://github.com/inclementweather/bfcompanionpy/blob/master/bfcompanion.py) ? (Just to find out if this is a problem with my account)

Edit: Url of "nucleus" is ok and return `code`, it's really a problem with credential
